contentsFolder: contents
pagesFolder: pages
postsFolder: posts
publicFolder: public
galleriesFolder: galleries
themeImageResolutions:
  retro:
    postThumbnail:
      width: 143
      aspectRatio: 16:9
      quality: 80
    contentImage:
      width: 350
      quality: 100
    galleryThumbnail:
      width: 120
      quality: 80
    galleryImage:
      width: 600
  modern:
    postThumbnail:
      width: 600
      aspectRatio: 16:9
    contentImage:
      width: 650
    galleryThumbnail:
      width: 150
